/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as TripsIndexRouteImport } from './routes/trips.index'
import { Route as TripsSlugRouteImport } from './routes/trips.$slug'
import { Route as ApiPublicSiteImageSplatRouteImport } from './routes/api/public/site-image.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const TripsIndexRoute = TripsIndexRouteImport.update({
  id: '/trips/',
  path: '/trips/',
  getParentRoute: () => rootRouteImport,
} as any)
const TripsSlugRoute = TripsSlugRouteImport.update({
  id: '/trips/$slug',
  path: '/trips/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSiteImageSplatRoute = ApiPublicSiteImageSplatRouteImport.update({
  id: '/api/public/site-image/$',
  path: '/api/public/site-image/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/trips/$slug': typeof TripsSlugRoute
  '/trips/': typeof TripsIndexRoute
  '/api/public/site-image/$': typeof ApiPublicSiteImageSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/trips/$slug': typeof TripsSlugRoute
  '/trips': typeof TripsIndexRoute
  '/api/public/site-image/$': typeof ApiPublicSiteImageSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/trips/$slug': typeof TripsSlugRoute
  '/trips/': typeof TripsIndexRoute
  '/api/public/site-image/$': typeof ApiPublicSiteImageSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/contact'
    | '/trips/$slug'
    | '/trips/'
    | '/api/public/site-image/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/contact'
    | '/trips/$slug'
    | '/trips'
    | '/api/public/site-image/$'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/contact'
    | '/trips/$slug'
    | '/trips/'
    | '/api/public/site-image/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ContactRoute: typeof ContactRoute
  TripsSlugRoute: typeof TripsSlugRoute
  TripsIndexRoute: typeof TripsIndexRoute
  ApiPublicSiteImageSplatRoute: typeof ApiPublicSiteImageSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trips/': {
      id: '/trips/'
      path: '/trips'
      fullPath: '/trips/'
      preLoaderRoute: typeof TripsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trips/$slug': {
      id: '/trips/$slug'
      path: '/trips/$slug'
      fullPath: '/trips/$slug'
      preLoaderRoute: typeof TripsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/site-image/$': {
      id: '/api/public/site-image/$'
      path: '/api/public/site-image/$'
      fullPath: '/api/public/site-image/$'
      preLoaderRoute: typeof ApiPublicSiteImageSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ContactRoute: ContactRoute,
  TripsSlugRoute: TripsSlugRoute,
  TripsIndexRoute: TripsIndexRoute,
  ApiPublicSiteImageSplatRoute: ApiPublicSiteImageSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
